SELECT * FROM SHOPPINGMALL.BUY;
SELECT * FROM SHOPPINGMALL.BUY_LIST;
SELECT * FROM SHOPPINGMALL.CART;
SELECT * FROM SHOPPINGMALL.CATEGORY;
SELECT * FROM SHOPPINGMALL.MEMBER;
SELECT * FROM SHOPPINGMALL.PRODUCT;