USE OMOK;

DROP TRIGGER IF EXISTS INSERT_USER;

DELIMITER ?!
CREATE TRIGGER INSERT_USER AFTER INSERT
ON USER
FOR EACH ROW
BEGIN
    DECLARE _U_NAME VARCHAR(10);
    
    SET _U_NAME = (
					SELECT U_NAME
                    FROM USER
                    WHERE U_NUM = NEW.U_NUM);
	INSERT INTO SCORE(S_POSITION, S_U_NUM) VALUES
		("BLACK", "_U_NAME"), ("WHITE", "_U_NAME");
END ?!
DELIMITER ;